







const express = require("express");
const router = express.Router();
const adminController = require("../controllers/predefine.controller");
const { isAuth, isAdmin } = require("../middleware/isAuth");

// Create or update slot templates
router.post("/slots", isAuth, isAdmin, adminController.createSlotTemplate);

// Auto-generate dates for next 10 days
router.post("/auto-generate-dates", isAuth, isAdmin, adminController.autoGenerateDates);

// Get all slot templates
router.get("/slot-templates", isAuth, isAdmin, adminController.getAllSlotTemplates);

// Get specific slot template by date
router.get("/slot-template/:date", isAuth, isAdmin, adminController.getSlotTemplateByDate);

// Update slot template for specific date
router.put("/slot-template/:date", isAuth, isAdmin, adminController.updateSlotTemplate);

// Delete slot template for a specific date
router.delete("/slot-template/:date", isAuth, isAdmin, adminController.deleteSlotTemplateByDate);

// Clean up past dates
router.post("/cleanup-past-dates", isAuth, isAdmin, adminController.cleanupPastDates);

// Get next available dates for auto-generation
router.get("/next-available-dates", isAuth, isAdmin, adminController.getNextAvailableDates);

module.exports = router;
